name: californiaefficiencygroup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_state_notifier: ^0.7.0
  freezed_annotation: ^1.1.0
  provider: ^6.0.0
  state_notifier: ^0.7.0

  # HTTP
  chopper: ^4.0.4
  logging: ^1.0.2

  # Firebase - https://firebase.flutter.dev
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_messaging: ^11.2.4
  firebase_remote_config: ^1.0.3
  firebase_database: ^9.0.5


  # Notifications
  flutter_local_notifications: ^9.2.0

  # Storage
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.11

  # Url launcher
  url_launcher: ^6.0.17
  flutter_linkify: ^5.0.2

  # View
  shimmer: ^2.0.0
  photo_view: ^0.13.0

  # Util
  quiver: ^3.0.1
  flutter_svg: ^1.0.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  fl_chart: ^0.40.6
  cached_network_image: ^3.0.0
  supercharged: ^2.0.0
  package_info: ^2.0.2
  get_it: ^7.1.3
  keyboard_actions: ^3.4.0
  path_provider: ^2.0.8

  cupertino_icons: ^1.0.3
  carousel_slider: ^4.0.0-nullsafety.0
  firebase_storage: ^10.2.5
  randexp: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  build_web_compilers:
  flutter_lints: ^1.0.0
  chopper_generator: ^4.0.3
  json_serializable: ^6.1.3
  freezed: ^1.0.0

  pedantic_mono: ^1.15.0

  # tools
  flutter_launcher_icons: ^0.9.2

# flutter_icons:
#   image_path: 'assets/(logo_name).png'
#   android: true
#   ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/text/
